// Copyright © 2026 Neil Colvin.
// Licensed under the MIT License with Commons Clause. See LICENSE file in the project root for full license information.

using Crestron.DeviceDrivers.SDK.EntityModel.Attributes;

namespace WiserHeat.CrestronDriver;

[EntityDataType (Id = "crestron:DeviceUxCategory")]
public enum DeviceUxCategory
	{
	Other,
	Amplifier,
	Appliance,
	Area,
	AudioMixer,
	AudioProcessor,
	AvReceiver,
	AvSwitcher,
	AudioSwitcher,
	BlurayPlayer,
	CableBox,
	Camera,
	Display,
	Fan,
	Fireplace,
	GameConsole,
	GarageDoor,
	Group,
	Hvac,
	Intercom,
	IrrigationSystem,
	Light,
	Lock,
	NetworkRouter,
	NetworkSwitch,
	Outlet,
	Platform,
	Pool,
	PoolController,
	PowerController,
	Printer,
	Projector,
	ProjectorLift,
	ProjectorScreen,
	Room,
	Scene,
	SecuritySystem,
	Sensor,
	Shade,
	SignagePlayer,
	Spa,
	Streamer,
	Switch,
	Thermostat,
	Tuner,
	Tv,
	Ventilation,
	VideoPlayer,
	VideoProcessor,
	VideoWallProcessor,
	VideoWallScreen,
	VirtualDevice,
	VoiceAssistant,
	VolumeControl,
	Weather,
	Whiteboard,
	Window,
	WirelessAccessPoint
	}
